name: Automatic backport pull requests

on:
  pull_request_target:
    types:
      - labeled
      - closed

jobs:
  backport:
    name: Create backport pull requests
    if: github.event.pull_request.merged == true && !(contains(github.event.pull_request.labels.*.name, 'backport'))
    runs-on: ubuntu-latest
    steps:
      - name: Backporting
        uses: sorenlouv/backport-github-action@v9.5.1
        with:
          # github_token requires a token that has write permissions to the following:
          # Contents, Pull Requests, Workflows
          github_token: ${{ secrets.BACKPORT_TOKEN }}
          auto_backport_label_prefix: backport-to-

      - name: Log output on success
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Log output on failure
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log
